site_name: DataTorrent Documentation
theme: readthedocs
pages:
- DataTorrent RTS: index.md
- dtAssemble - Graphical Application Builder: app_builder.md
- dtDashboard - Application Data Visualization: visualize.md
- dtIngest - Unified Batch and Streaming Ingestion: ingestion.md
- Apache Apex:
    - Apache Apex: apex.md
    - Apache Apex-Malhar: malhar.md
- Sandbox: sandbox.md
- Demos: 
    - Sales - Transform, Analyze and Alert : sales_demo.md
    - Video Demos: video_demos.md
- Additinal Docs: additional_docs.md
